version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: seedmart-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: seedmart-frontend:latest
    ports:
      - "80:3000"
    depends_on:
      - backend

networks:
  default:
    driver: bridge
