version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"  # For development access
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=5000  # Explicitly set PORT for Render compatibility
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"   # HTTP
      - "443:3000"  # HTTPS
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:5000

  db:
    image: postgres:14
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
